add typescript
lamcgregor/valheim-frontend pull request #1
Opened 2021-02-16 22:05 UTC by tobold

2021-02-16 23:00 UTC, lamcgregor requested changes
The only necessary change is the `disabled` logic

2021-02-16 23:01 UTC, lamcgregor commented
There's also a conflict with App.js?

2021-02-16 23:35 UTC, tobold commented on src/App.tsx
> +          disabled={Object.values(Status).includes(status)}
yeah 🤦 this was the bug I mentioned on discord. I added this before adding the `TERMINATED `state. That's the only state when the button should work

2021-02-16 23:36 UTC, tobold commented on src/App.tsx
> +  const [players, updatePlayerList] = useState<string>("Loading");
> There's also a conflict with App.js?

hmm I rebased and should have fixed it. Will look tomorrow

2021-02-17 10:08 UTC, tobold commented on src/App.tsx
> +          disabled={Object.values(Status).includes(status)}
ok, fixed now

2021-02-17 14:11 UTC, lamcgregor commented on src/App.tsx
> +        {status === Status.LOADING ? (
nit: I'd say this should just conditionally render the button if the `status !== LOADING` as it will stop the other two calls from displaying if the status call is the last one to respond

2021-02-17 14:11 UTC, lamcgregor commented on src/App.tsx
> +  try {
Any reason we're doing a try/catch rather than the promise `.then`/`.catch`?

2021-02-17 14:13 UTC, lamcgregor commented on src/App.tsx
> +      return callback(text as Status);
Yeah I realised this after I made my comment that the responses from the `/connected` and `/recent` endpoints are not a status so we'd have to cast them.

I'm ok with this although it is probably super bad practice.

But so is the backend returning just strings

2021-02-17 15:12 UTC, tobold commented on src/App.tsx
> +  try {
I think just personal preference, think it's more readable. I'm not actually sure what would be throwing an error here

2021-02-17 17:11 UTC, lamcgregor commented on src/App.tsx
> +        {status === Status.LOADING ? (
I've also noted that the three calls return at quite different speeds and so each of the three state variables update separately. This logic hides everything based on only the `status` state, so if the `playerCount` or `players` are updated before `status` they still will not be visible until `status` is updated.

2021-02-17 17:11 UTC, lamcgregor commented on src/App.tsx
> +  try {
Fair enough :+1:

2021-02-17 17:30 UTC, tobold commented on src/App.tsx
> +        {status === Status.LOADING ? (
ok new change addresses this

2021-02-17 17:53 UTC, lamcgregor approved these changes

2021-02-17 17:55 UTC, merged